# Generated by Django 5.1 on 2025-01-19 08:27

from django.db import migrations

def create_default_customer(apps, schema_editor):
    Customer = apps.get_model('services', 'Customer')
    if not Customer.objects.exists():
        Customer.objects.create(
            name="Default Customer",
            email="default@example.com",
            phone="0000000000"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_customer),
    ]
